### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by singhpratyush** [iiitv/Odyssy#56]
Come up with different implementations and post screenshot here before opening PR.

**Comment by geekyJock8** [comment]
I have a suggestion, we should make a page for contact us if possible. The home page is cluttered with contact information. This includes the Map, Phone, Email at the top; and address, links to social media at the bottom. This information is important but it's not that frequently used. The only thing I would argue is that maybe phone no. is required and rather than having an icon, the phone no. should be present in text format. The footer can contain that information of phone no. and it should be left as clean and minimal as possible.

**Comment by singhpratyush** [comment]
@geekyJock8: Regarding the footer, would you like to submit a patch? If no, please give your suggestions at https://gitter.im/iiitv/Odyssy so that someone else can follow up.

And for the contact us page, please open an issue.

**Comment by geekyJock8** [comment]
I would like to submit a patch but as of now, I'm having problems with setting up the system. If I'm unable to set up the system soon, I'll post the design suggestion with full details on gitter.

**Comment by Monal5031** [comment]
@geekyJock8 sir any other changes which I didn't include in my PR needed? Otherwise lets close this issue.
